### ISSUE TITLE
Port to GTK3

### ISSUE THREAD

**Issue by alexandrucosminmihai** [sugarlabs/flipsticks#2] opened 2018-02-16 13:46 UTC
I would like to try to port this activity to GTK3

**Comment by quozl** [comment] 2018-02-17 00:48
Thanks.  When you do, please also;

- [ ] use the `sugar-toolkit-gtk3` classes instead of the bundled `toolkit` classes in this repository,
- [ ] move into the top level directory any `toolkit` classes that are not in `sugar-toolkit-gtk3`,
- [ ] remove the bundled `toolkit` classes,
- [ ] test the ported activity and document your test environment in your commit.

Looking forward to seeing your work.

**Comment by quozl** [comment] 2018-02-19 20:11
Recommend that you not try to port the `toolkit` classes until you have proved that they are not in `sugar-toolkit-gtk3`.

The activity was written to be Sugar version independent by a contributor who was very good at doing that.  For the activity to be installed on a very old Sugar version, where certain toolkit features are absent, the contributor added newer Sugar toolkit features into the activity.

So there is some duplication between `toolkit` in this activity and the `sugar-toolkit` sources.

As the issue is porting to GTK+ 3; a move from `sugar-toolkit` to `sugar-toolkit-gtk3`, you should check for and remove this duplication.  Otherwise the code will suffer from two future problems;

* features or bug fixes in `sugar-toolkit-gtk3` won't be effective in the activity, leading to issues being reported,
* further porting to GTK+ 4 expected within a few years will be more expensive than it needs to be; because there will be more lines of code to port and review.

You should also use flake8 to correct any problems.  One of the problems is wildcard imports, which makes it harder to do this port.  See https://github.com/sugarlabs/sugar-docs/blob/ee2f983b35d7821971ba3f6422e8ba834c4755ec/src/desktop-activity.md#coding-standards

**Comment by alexandrucosminmihai** [comment] 2018-02-20 06:40
Thank you very much for this information! Things are clearer in my mind now. I still want to work on this issue, but it will probably take me some time. I hope this is not a problem.

**Comment by quozl** [comment] 2018-02-20 07:33
No problem.  If there is a delay, check the commits, branches and forks before you begin work; in case someone else has done work on it.

**Comment by yell0wfl4sh** [comment] 2018-06-26 18:53
WIP: see https://github.com/yashagrawal3/flipsticks/tree/gtk3

**Comment by JuiP** [comment] 2020-08-10 08:28
#6 merged, closes this issue :)
@quozl @chimosky

**Closed as completed** 2020-08-11 05:52 UTC
